db.url=#place db url here
db.user=#place db user here
db.password=#place db password here
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver #change it to your own db server driver

app.starting_view=teacher_form.fxml
