db.url=jdbc:sqlserver://localhost:1433;databaseName=FacultyEval;encrypt=true;trustServerCertificate=true;
db.user=java_app
db.password=12345
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

app.starting_view=CreateQuestioner.fxml